"""Refuse a deploy that changes behaviour without bumping `demo_version` (§6).

    uv run python -m contracts.check_version_bump            # verify
    uv run python -m contracts.check_version_bump --record   # after a deploy

THE FAILURE THIS PREVENTS. `demo_version` is hand-maintained on purpose
(see `version.py`), and the cost of hand-maintenance is that it is forgotten
exactly when it matters: the late change the night before, deployed in a hurry.
Trace history then contains two builds that answer differently under one
version, and "compare v3 against v4" silently stops being a question with an
answer. Nothing else in the build detects that — the agent works fine, it just
lies about which build it is.

HOW IT WORKS. `contracts/.deployed.json` records the `demo_version` that was
last deployed and a SHA-256 of every behaviour-bearing file at that moment.
Before a deploy, this recomputes those hashes:

    files changed + version unchanged   -> FAIL, bump it
    files changed + version bumped      -> pass
    files unchanged + version bumped    -> pass, warn (a bump with no change
                                           is harmless but usually a mistake)
    nothing changed                     -> pass

WHAT COUNTS AS BEHAVIOUR-BEARING. §6 names `contracts/grants.py`,
`instructions.md`, `skills/` and `middleware/`. This also watches `agent.py`,
`tools/` and `context_schema.py`, because a model change, a tool change or a
context change alters what a run does just as surely — and a check that misses
those would pass on the most likely late edit of all. Tests, comments and the
eval harness are deliberately absent: they cannot change an answer.

WHY NOT DERIVE THE VERSION FROM THESE HASHES. Then it would change on a
whitespace edit, and the whole argument in `version.py` for a deliberate
number would be lost. The hashes decide WHEN A HUMAN MUST CHOOSE, not what
they choose.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

from contracts.version import DEMO_VERSION

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATE = ROOT / "contracts" / ".deployed.json"

#: Paths whose contents can change what a run does. Directories are walked.
WATCHED = [
    "agent.py",
    "context_schema.py",
    "instructions.md",
    "contracts/grants.py",
    "contracts/roles.py",
    "contracts/version.py",
    "middleware",
    "skills",
    "tools",
]


def digest() -> dict[str, str]:
    """path -> sha256, for every watched file that exists."""
    out: dict[str, str] = {}
    for entry in WATCHED:
        p = ROOT / entry
        if p.is_file():
            files = [p]
        elif p.is_dir():
            files = sorted(f for f in p.rglob("*.py") if "__pycache__" not in f.parts)
            files += sorted(p.rglob("*.md"))
        else:
            continue
        for f in sorted(set(files)):
            out[str(f.relative_to(ROOT))] = hashlib.sha256(f.read_bytes()).hexdigest()
    return out


def load() -> dict:
    if not STATE.exists():
        return {}
    return json.loads(STATE.read_text())


def record() -> int:
    STATE.write_text(
        json.dumps(
            {
                "_generated": "GENERATED by contracts/check_version_bump.py --record "
                              "immediately after a successful deploy. Do not edit.",
                "demo_version": DEMO_VERSION,
                "files": digest(),
            },
            indent=2,
        )
        + "\n"
    )
    print(f"recorded {DEMO_VERSION} over {len(digest())} files -> {STATE.name}")
    return 0


def main() -> int:
    if "--record" in sys.argv:
        return record()

    prev = load()
    if not prev:
        print(
            "no deploy recorded yet — nothing to compare against.\n"
            "After the next successful deploy, run:\n"
            "    uv run python -m contracts.check_version_bump --record"
        )
        return 0

    now, before = digest(), prev.get("files", {})
    changed = sorted(
        set(now) ^ set(before)
        | {p for p in set(now) & set(before) if now[p] != before[p]}
    )
    bumped = DEMO_VERSION != prev.get("demo_version")

    if changed and not bumped:
        print(
            f"FAIL: {len(changed)} behaviour-bearing file(s) changed since "
            f"{prev['demo_version']} was deployed, but demo_version is still "
            f"{DEMO_VERSION}.\n"
        )
        for p in changed:
            print(f"    {p}")
        print(
            "\nEvery run of the new build would claim to be the old one, and the "
            "traces would be uncomparable.\nEdit contracts/version.py: bump "
            f"DEMO_VERSION past {DEMO_VERSION} and add a HISTORY line."
        )
        return 1

    if changed:
        print(f"OK: {len(changed)} file(s) changed, demo_version "
              f"{prev['demo_version']} -> {DEMO_VERSION}")
        for p in changed:
            print(f"    {p}")
        return 0

    if bumped:
        print(f"OK (but odd): demo_version {prev['demo_version']} -> {DEMO_VERSION} "
              "with no behaviour-bearing file changed. Harmless; usually a mistake.")
        return 0

    print(f"OK: nothing behaviour-bearing changed since {DEMO_VERSION} was deployed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
