"""Project contracts/grants.py into contracts/grants.json for the UI (C2).

Python stays the source of truth; this is a generated projection. CI asserts
regenerating produces no diff, so the UI can never hold a second opinion about
what a role may reach.

Run:  python -m contracts.emit_grants_json
"""

from __future__ import annotations

import json
import pathlib

from contracts.grants import (
    CORPORA,
    CORPUS_BLURB,
    ROLE_LABELS,
    granted_prefixes,
    primary_order,
    withheld_prefixes,
)
from contracts.roles import ROLES
from contracts.version import DEMO_VERSION

OUT = pathlib.Path(__file__).with_name("grants.json")

HEADER = "GENERATED by contracts/emit_grants_json.py — do not edit by hand."


def build() -> dict:
    return {
        "_generated": HEADER,
        "demo_version": DEMO_VERSION,
        "roles": {
            role: {
                "label": ROLE_LABELS[role],
                # `order` is the preference ordering, `granted` the unordered
                # surface, `withheld` what the role cannot reach. All three are
                # emitted so the UI renders them without deriving anything.
                "granted": sorted(granted_prefixes(role)),
                "order": list(primary_order(role)),
                "withheld": sorted(withheld_prefixes(role)),
            }
            for role in ROLES
        },
        "corpora": {prefix: CORPUS_BLURB[prefix] for prefix in CORPORA},
    }


def main() -> None:
    # ensure_ascii=False keeps the em-dash and middot literal, so the file is
    # readable in a diff and in the UI rather than a wall of \\u escapes.
    OUT.write_text(
        json.dumps(build(), indent=2, sort_keys=False, ensure_ascii=False) + "\n"
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
